# Language-specific VS Code extensions and settings configuration

terraform:
  extensions:
    - hashicorp.terraform
    - ms-vscode.terraform
  settings:
    terraform.experimentalFeatures.validateOnSave: true
    terraform.experimentalFeatures.prefillRequiredFields: true
    "files.associations":
      "*.tf": "terraform"
      "*.tfvars": "terraform"
      "*.hcl": "terraform"
    "[terraform]":
      "editor.defaultFormatter": "hashicorp.terraform"
      "editor.formatOnSave": true

python:
  extensions:
    - ms-python.python
    - ms-python.vscode-pylance
    - ms-python.isort
  settings:
    "python.defaultInterpreterPath": "./venv/bin/python"
    "python.linting.enabled": true
    "python.linting.pylintEnabled": true
    "[python]":
      "editor.formatOnSave": true
      "editor.defaultFormatter": "ms-python.python"
      "editor.codeActionsOnSave":
        "source.organizeImports": "explicit"

go:
  extensions:
    - golang.go
  settings:
    "[go]":
      "editor.formatOnSave": true
      "editor.tabSize": 4
      "editor.insertSpaces": false

markdown:
  extensions:
    - yzhang.markdown-all-in-one
    - DavidAnson.vscode-markdownlint
    - bierner.markdown-mermaid
    - bierner.markdown-preview-github-styles
  settings:
    "files.associations":
      "*.md": "markdown"
      "*.mdx": "markdown"
      "*.markdown": "markdown"
    "[markdown]":
      "editor.wordWrap": "on"
      "editor.wordWrapColumn": 100
      "editor.quickSuggestions":
        comments: "off"
        strings: "off"
        other: "off"
      "editor.formatOnSave": true
      "editor.formatOnPaste": true
      "editor.tabSize": 2
      "editor.insertSpaces": true
      "editor.defaultFormatter": "yzhang.markdown-all-in-one"
    "markdown.preview.breaks": true
    "markdown.preview.linkify": true
    "markdown.preview.typographer": true
    "markdown.extension.toc.updateOnSave": true
    "markdown.extension.toc.orderedList": false
    "markdown.extension.list.indentationSize": "adaptive"
    "markdownlint.config":
      MD013: false  # Line length
      MD033: false  # Allow inline HTML
      MD041: false  # First line should be top level header

yaml:
  extensions:
    - redhat.vscode-yaml
  settings:
    "files.associations":
      "*.yml": "yaml"
      "*.yaml": "yaml"
    "[yaml]":
      "editor.formatOnSave": true
      "editor.tabSize": 2
      "editor.insertSpaces": true
    "yaml.format.enable": true
    "yaml.validate": true
    "yaml.hover": true
    "yaml.completion": true

json:
  extensions:
    - ms-vscode.json
  settings:
    "[json]":
      "editor.formatOnSave": true
      "editor.tabSize": 2
      "editor.insertSpaces": true
    "[jsonc]":
      "editor.formatOnSave": true
      "editor.tabSize": 2
      "editor.insertSpaces": true

shell:
  extensions:
    - timonwong.shellcheck
    - foxundermoon.shell-format
  settings:
    "files.associations":
      "*.sh": "shellscript"
      "*.bash": "shellscript"
      "*.zsh": "shellscript"
    "[shellscript]":
      "editor.formatOnSave": true
      "editor.tabSize": 4
      "editor.insertSpaces": true
    "shellcheck.enable": true
    "shellformat.effectLanguages":
      - "shellscript"

powershell:
  extensions:
    - ms-vscode.powershell
  settings:
    "files.associations":
      "*.ps1": "powershell"
      "*.psm1": "powershell"
      "*.psd1": "powershell"
    "[powershell]":
      "editor.formatOnSave": true
      "editor.tabSize": 4
      "editor.insertSpaces": true

sql:
  extensions:
    - ms-mssql.mssql
  settings:
    "files.associations":
      "*.sql": "sql"
    "[sql]":
      "editor.formatOnSave": true
      "editor.tabSize": 2
      "editor.insertSpaces": true